services:
  strapi:
    image: ghcr.io/viva-la-vita/api:development
    build:
      context: .
      target: base
    environment:
      NODE_ENV: development
    env_file:
      - .env
    volumes:
      - .:/app
