version: "3"
services:
  strapi:
    container_name: strapi
    build:
      context: ./strapi
      dockerfile: Dockerfile.production
    restart: unless-stopped
    env_file: .env.production
    environment:
      DATABASE_CLIENT: ${DATABASE_CLIENT}
      DATABASE_HOST: mysql
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      ADMIN_JWT_SECRET: ${ADMIN_JWT_SECRET}
      NODE_ENV: ${NODE_ENV}
      API_TOKEN_SALT: ${API_TOKEN_SALT}
      APP_KEYS: ${APP_KEYS}
      PORT: ${PORT}
      HOST: ${HOST}
    ports:
      - "1337:1337"
    networks:
      - cms
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0.29
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_USER: ${DATABASE_USERNAME}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
    expose:
      - 3306
    volumes:
      - mysql:/var/lib/mysql
    networks:
      - cms

volumes:
    mysql:

networks:
  cms:
    name: CMS
    driver: bridge
