services:
  strapi:
    image: ghcr.io/viva-la-vita/api:development
    build:
      context: .
      target: base
    environment:
      NODE_ENV: development
      APP_KEYS: ${APP_KEYS}
      API_TOKEN_SALT: ${API_TOKEN_SALT}
      ADMIN_JWT_SECRET: ${ADMIN_JWT_SECRET}
      JWT_SECRET: ${JWT_SECRET}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - .:/app

  admin:
    image: nginx:1.23-alpine
    build:
      context: .
      target: cms
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www/
