version: "3"

services:
  strapi:
    image: ghcr.io/viva-la-vita/api
    restart: always
    environment:
      NODE_ENV: production
    env_file:
      - .env
    ports:
      - 3000:3000
    depends_on:
      - mysql

  admin:
    image: ghcr.io/viva-la-vita/cms
    restart: always
    ports:
      - 3001:80
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: strapi
      MYSQL_USER: strapi
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
    expose:
      - 3306
    volumes:
      - mysql:/var/lib/mysql

volumes:
  mysql:
