services:
  strapi:
    image: ghcr.io/viva-la-vita/api
    restart: always
    environment:
      NODE_ENV: production

  admin:
    image: ghcr.io/viva-la-vita/cms
    restart: always
    ports:
      - 3000:80
