FROM node:16

# Installing libvips-dev for sharp Compatability
RUN apt-get update && apt-get install libvips-dev -y

WORKDIR /opt/app

COPY ./ .

RUN npm i

RUN npm run build

CMD ["npm", "run", "start"]
