name: Build API

on:
  push:
    branches: [master]

env:
  API: ghcr.io/viva-la-vita/api

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login to ghcr.io
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: viva-la-vita
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and push API
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ env.API }}
          target: api
          cache-from: type=registry,ref=${{ env.API }}:buildcache
          cache-to: type=registry,ref=${{ env.API }}:buildcache,mode=max
